apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template-new
  description: A template that utilizes query string parameters
spec:
  owner: team@example.com
  type: service

  # Define the inputs for the template
  parameters:
    - title: 'Component Name'
      name: 'componentName'
      description: 'The name of the component'
      type: string
      default: '{{ query.componentName }}'
      required: true

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.componentName }}!'
