apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: my-template
  description: A template that utilizes query string parameters
spec:
  owner: team@example.com
  type: service

  # Define the inputs for the template
  parameters:
    - title: 'Component Name'
      name: 'componentName'
      description: 'The name of the component'
      type: string
      default: '{{ query.componentName }}'
      required: true


  steps:
    - id: 'generate'
      name: 'Generate Component'
      action: 'my-custom-action'
      input:
        componentName: '{{ parameters.componentName }}'
